//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPFileManagament
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class FTPConnectionInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FTPConnectionInfo()
        {
            this.FTPFileInfoes = new HashSet<FTPFileInfo>();
        }

        public int Id { get; set; }
        public string ConnName { get => name; set { name = value; UpdateProp(); } }
        string name;

        public string ConnIP { get => ipAddr; set { ipAddr = value; UpdateProp(); } }
        public string ipAddr = "";
        public Nullable<int> ConnPort { get => port; set { port = value; UpdateProp(); } }
        int? port = 21;
        public string ConnUsername { get => username; set { username = value; UpdateProp(); } }
        string username = "";
        public string ConnPassword { get => password; set { password = value; UpdateProp(); } }
        string password = "";

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FTPFileInfo> FTPFileInfoes { get; set; }
        public bool CanUserDelete { get; set; } = true;
        public string FullName { get => $"{ConnName} ({ConnIP})"; }

        public event PropertyChangedEventHandler PropertyChanged;
        protected void UpdateProp([CallerMemberName] string name = null) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
    }
}

