//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPFileManagament
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FTPDBContext : DbContext
    {
        public FTPDBContext()
            : base("name=FTPDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FTPConnectionInfo> FTPConnectionInfoes { get; set; }
        public virtual DbSet<FTPFileInfo> FTPFileInfoes { get; set; }
        public virtual DbSet<FTPFileVersion> FTPFileVersions { get; set; }
    }
}
