//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPFileManagament
{
    using System;
    using System.Collections.Generic;

    public partial class FTPFileVersion
    {
        public int Id { get; set; }
        public int FileId { get; set; }
        public double FileVersion { get; set; }
        public string RemotePath { get; set; }
        public string Descr { get; set; }
        public long Size { get; set; }
        public long LastModified { get; set; }
        public byte[] HashCode { get; set; }

        public string FileSize => Math.Round((double)(Size) / 1024).ToString() + " KB";
        public string LastMod => new DateTime(LastModified).ToString("dd-MMM-yyyy HH:mm");

        public virtual FTPFileInfo FTPFileInfo { get; set; }
    }
}
